{
  "table":
  [
    {
      "class_":"SPSC", 
      "name":"Supplier",
      "fields":{ 
        "SupplierID":["INCREMENTID","primary"], 
        "SupplierName":"COMPANYNAME",
        "ContactName":"CHINESENAME",
        "ContactPhone":"tel",
        "Address":"address"
        },
      "fake_amount":5,
    },
    {
      "class_":"SPSC",
      "name":"Product",
      "fields":{
        "ProductID":["INCREMENTID","primary"],
        "ProductName":"ee",
        "Unit":"unit",
        "UnitPrice":"price"
        },
      "fake_amount":10,
    },

    {
      "class_":"SPSC",
      "name":"PurchaseOrder",
      "fields":{
        "PurchaseOrderID":"INCREMENTID",
        "OrderDate":"RANDOMDATE",
        "SupplierID":["out","Supplier"],
        "TotalAmount":"float(100,300)"
        },
      "fake_amount":10,
    },

    {
      "class_":"SPSC",
      "name":"PurchaseOrderDetail",
      "fields":{
        "PurchaseOrderID":["out","PurchaseOrder","primary"],
        "ProductID":["out","Product"],
        "Quantity":"int(1,100)",
        "SupplierName":["out","Supplier"],
        "UnitPrice":"float(1,100)"
        },
      "fake_amount":10,
    },

    {
      "class_":"SPSC",
      "name":"Receipt",
      "fields":{
        "ReceiptID":["INCREMENTID","primary"],
        "ReceiptDate":"ReceiptDate",
        "PurchaseOrderID":["out","PurchaseOrder"],
        "SupplierID":["out","Supplier"]
        },
      "fake_amount":10,
    },

    {
      "class_":"SPSC",
      "name":"ReceiptDetail",
      "fields":{
        "ReceiptID":["out","Receipt","primary"],
        "ProductID":["out","Product"],
        "Quantity":"int(200,300)",
        "UnitPrice":["out","Product"]
        },
      "fake_amount":10,
    },

    {
      "class_":"SPSC",
      "name":"Invoice",
      "fields":{
        "InvoiceID":["INCREMENTID","primary"],
        "InvoiceDate":"InvoiceDate",
        "PurchaseOrderID":["out","PurchaseOrder"],
        "SupplierID":["out","Supplier"],
        "TotalAmount":"float(100,200)"
        },
      "fake_amount":10,
    },

    {
      "class_":"SPSC",
      "name":"InvoiceDetail",
      "fields":{
        "InvoiceID":["out","Invoice","primary"],
        "ProductID":["out","Product"],
        "Quantity":"int(1,10)",
        "UnitPrice":["out","Product"]
        },
    "fake_amount":10,
    }
  ],

  "datarule":
  [
    {
      "name":"ADDRESS",
      "class_":"ADDRESS"
    },
    {
      "name":"CHINESENAME",
      "class_":"CHINESENAME"
    },
    {
      "name":"COMPANYNAME",
      "class_":"COMPANYNAME"
    },
    {
      "name":"RANDOMDATE",
      "class_":"RANDOMDATE"
    },
    {
      "name":"RECEIPTDATE",
      "class_":"RECEIPTDATE"
    },
     {
      "name":"INVOICEDATE",
      "class_":"INVOICEDATE"
    },
    {
      "name":"EE",
      "class_":"EE"
    },
    {
      "name":"TEL",
      "class_":"TEL"
    },
    {
      "name":"UNIT",
      "class_":"UNIT"
    },
    {
      "name":"UUID",
      "class_":"UUID"
    },
    {
      "name":"NUMERICAL",
      "class_":"NUMERICAL"
    },
    {
      "name":"INCREMENTID",
      "class_":"INCREMENTID"
    },
     {
      "name":"PRICE",
      "class_":"PRICE"
    }
  ]
}
